### ISSUE TITLE
Enhance All.cshtml to display Articles in grid view

### ISSUE THREAD

**Issue by emo333** [csharpfritz/CoreWiki#107]
Since this UI displays all of the articles (paged) and each article element consists of a relative small size of textual data, it seems to make good UI sense not to display each article spanning an entire "row" of the screen.

**Comment by emo333** [comment]
I would like to take this on. 😊  Will also apply it on Search page since it displays the list of Articles in same manor.

**Comment by emo333** [comment]
#110

**Comment by c17r** [comment]
@csharpfritz #110 has been merged, so this should probably be closed.
