### ISSUE TITLE
Need a page size selector 

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/CoreWiki#109]
Needed on:
 - [ ] All Articles
 - [ ] Latest Articles

**Comment by emo333** [comment]
I see some commented lines in All.cshtml line 13 [https://github.com/csharpfritz/CoreWiki/blob/dev/CoreWiki/Pages/All.cshtml] that are possibly the page size selector code you were wondering what happened to?

**Comment by csharpfritz** [comment]
That sure looks like it...  would you like to uncomment and test those
lines?



Jeff
