### ISSUE TITLE
WordCount returns an inaccurate count

### ISSUE THREAD

**Issue by parithon** [csharpfritz/CoreWiki#111]
WordCount returns 8 when, as example, the HomePage has 9 words.

https://github.com/csharpfritz/CoreWiki/blob/3231aaab2c8b7e450d531a2fbd41de78b8efae71/CoreWiki/Helpers/StringHelpers.cs#L26

**Comment by essenbee** [comment]
I think that counting spaces is the reason for this, but overall, as a way of estimating reading time, I believe its fine to be off by one here, especially given that this technique doesn't allocate lots of strings on the heap, which the original method did. Jeff may think differently though ...

**Comment by parithon** [comment]
As trivial a bug this may be, if we initialize the `wordCount` with 1 instead of 0 it would squash the bug...

**Comment by mozts2005** [comment]
Given that this is intended to be a wiki which will support a number of syntax elements would we not need to account for them.

to support word count we would need to build a full syntax for all languages supported.  given this fact, My vote is to remove word count at this time.

**Comment by essenbee** [comment]
Its only used to estimate reading time, so its sufficient to have a simple approximation, I would argue.

**Comment by ashleybroughton** [comment]
It seems that moment.js has a word count and estimated reader time built into the editor control.  
Perhaps this can be adapted / used in place of the static helper methods.

**Comment by ashleybroughton** [comment]
Sorry, I wrote that comment based on my faulty memory. The code is actually a part of the simplemde status bar.

![image](https://user-images.githubusercontent.com/222825/41699916-b0cae348-7558-11e8-9486-92b7a64004b9.png)  
![image](https://user-images.githubusercontent.com/222825/41699958-ea1b2ee6-7558-11e8-9be8-ae97a8f5d11d.png)
