### ISSUE TITLE
External Login Bug

### ISSUE THREAD

**Issue by parithon** [csharpfritz/CoreWiki#115]
During the stream on Thursday, June 14th 2018 Jeff tried to add Twitter as an option for login but when you clicked on the Twitter button it wouldn't work. When I looked into the issue I figured out that the `value` attribute on the Twitter button (which would be the `provider` parameter) was never passed to the `ExternalLogin.cshml` `OnPost` method.

After further digging I narrowed the issue to the following code:
https://github.com/csharpfritz/CoreWiki/blob/7f32a8b9448d5a461bee7f76143a284ff29f7a7e/CoreWiki/wwwroot/js/site.js#L23-L26

I presume this is because the button is disabled prior to the Form's data getting serialized by the DOM and never getting sent to the `ExternalLogin.cshtml` `OnPost` method.

**Comment by csharpfritz** [comment]
This is fixed... thanks for your help!
