### ISSUE TITLE
Should not be able to delete the Home Page

### ISSUE THREAD

**Issue by essenbee** [csharpfritz/CoreWiki#120]
Not even Admins should not be able to delete the Home Page, only Edit it.

**Comment by ashleybroughton** [comment]
@csharpfritz, @essenbee 

Someone can still delete the home page if they manually navigate to the [delete URL](https://localhost:44333/home-page/delete), or make a POST to the delete endpoint for homepage. 

Can we please re-open this issue until it is resolved?

**Comment by ashleybroughton** [comment]
Please ignore previous comment. Seems to be working as expected now.
