### ISSUE TITLE
wiki.db should not be in Git repository

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/CoreWiki#14]

**Comment by DevOpsChallengeBr** [comment]
Hi, good discussion! I don't agree. I think the format proposal (binary .db) that is wrong.

**My suggestion:**

First of all, we have to switch to SQL Server 2017 (Preferably Docker Container). :

**Pros:**
1. Easy Maintenance
2. We can use the project of type Database project in Visual Studio
3. We can version and track changes in GitHub

  **Using Docker-Compose**
4. We can build (generate .DacPac File)
5. We can create Container (FROM microsoft/mssql-server-windows-express)
6. We can deploy .DacPac in container. The image could be disposable or persistent storage

**Optional**
7. We can execute an initial load of master data (post deployment) 
8. We can create an Test Project
9. We can write main user stories and automate them using speckflow
10. We can collect the results and present in some dashboard

cons:
 10. More complex to implement

---------------------------------------------------
@csharpfritz, What do you think about that? :)

**Sorry, my jungle English!**

**Comment by IvandroFabiaeFilhos** [comment]
Hi, good discussion! I don't agree. I think the format proposal (binary .db) that is wrong.

**My suggestion:**

First of all, we have to switch to SQL Server 2017 (Preferably Docker Container). :

**Pros:**
1. Easy Maintenance
2. We can use the project of type Database project in Visual Studio
3. We can version and track changes in GitHub

**Using Docker-Compose:**
4. We can build (generate .DacPac File)
5. We can create Container (FROM microsoft/mssql-server-windows-express)
6. We can deploy .DacPac in container. The image could be disposable or persistent storage

**Optional**
7. We can execute an initial load of master data (post deployment) 
8. We can create an Test Project
9. We can write main user stories and automate them using speckflow
10. We can collect the results and present in some dashboard

**Cons:**
 10. More complex to implement

---------------------------------------------------
@csharpfritz, What do you think about that? :)

**Sorry, my jungle English!**

**Comment by csharpfritz** [comment]
Love this idea...  let's get the basic functionality working, and then we can add SQL Server as a provider that an implementer can choose to use with the Wiki

**Comment by summer600** [comment]
I like the suggestion that @IvandroFabiaeFilhos gave as well but that is way beyond the scope of this issue. The wiki.db should not be checked in just as we do not check in the artifacts generated by bundleconfig. In this case we could also add the wiki.db of *.db to the .gitignore file.
In fact .gitignore already has entries to exclude SQL Server .mdf files so this would just be adding to that by excluding sqllite databases.
 
That would fix this issue. The @IvandroFabiaeFilhos  suggestions could then be used to create a new issue that is also *not* marked "goodfirstissue"
