### ISSUE TITLE
[Security] XSS issue when rendering article content and comments using markdown library

### ISSUE THREAD

**Issue by ashleybroughton** [csharpfritz/CoreWiki#144]
This could lead to some nefarious edits.

![image](https://user-images.githubusercontent.com/222825/41827410-e2121e88-7861-11e8-8df2-ebfa25719e30.png)

![image](https://user-images.githubusercontent.com/222825/41827421-e9a79ede-7861-11e8-8370-7783c51584da.png)

**Comment by ashleybroughton** [comment]
This should be fixed in most browsers by CSP when this is fully implemented. As for older browsers, we should be encoding the user input when saving it to the database and / or displaying the content.

**Comment by ashleybroughton** [comment]
In addition to the above example, <img> tags appear to be allowed which could allow someone to embed a remote image and track the users of the site.

Again, this will likely be fixed when we implement CSP fully, but ideally we should be encoding HTML, or implementing a markdown style syntax.

![image](https://user-images.githubusercontent.com/222825/41888344-92927e62-7937-11e8-82a7-ca78bd1a406a.png)

**Comment by ashleybroughton** [comment]
Another example 

![image](https://user-images.githubusercontent.com/222825/41892572-2a8904c6-794b-11e8-869d-4cf1108c78c2.png)

![image](https://user-images.githubusercontent.com/222825/41892581-37023754-794b-11e8-8f69-aa5616480b85.png)

**Comment by ashleybroughton** [comment]
I just noticed that we appear to be using the [Westwind.AspNetCore.Markdown](https://github.com/RickStrahl/Westwind.AspNetCore/tree/master/Westwind.AspNetCore.Markdown) package and the `<markdown .. />` tag for rendering the comments and article content.

Is this perhaps a bug in that framework?

**Comment by ashleybroughton** [comment]
![image](https://user-images.githubusercontent.com/222825/41898366-6f414040-795c-11e8-9fab-5a41779e5d82.png)

https://github.com/showdownjs/showdown/wiki/Markdown's-XSS-Vulnerability-(and-how-to-mitigate-it)

**Comment by essenbee** [comment]
Hi @ashleybroughton , I think Mr Strahl’s response to the issue you raised is rather naive. We need a better solution.

**Comment by ashleybroughton** [comment]
Hi @essenbee . I did try HtmlSanitizer quickly, but I don't have much experience with it. It just seemed to turn the resulting markdown HTML into encoded tags, which means it didn't get any kind of markdown features.

This is definitely something we need to find a good solution for.

**Comment by ashleybroughton** [comment]
[bob](/nicelink)
[some text](javascript:alert('malicious%20link'))

<a href="javascript:alert('xss')">some text</a>

> hello <a name="n"
> href="javascript:alert('xss')">*you*</a>


<blockquote>
 <p>hello <a name="n"
 href="javascript:alert('xss')"><em>you</em></a></p>
</blockquote>
