### ISSUE TITLE
Feature: Pager configuration

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/CoreWiki#167]
The pager tag helper should be able to take attributes that determine whether to show the previous, first page, last page, next page buttons

**Comment by aaronincincy** [comment]
I'm taking a stab at this.

First thought was to have attributes for: 
```xml
<pager
    navigation-button-visibility="Always|Never|Auto" 
    navigation-buttons="All|None|OnlyNextAndPrevious|OnlyFirstAndLast" />
```

- `navigation-button-visibility="Never"` would have the same effect as `navigation-buttons="Neither"`, showing only the individual page number buttons.
- `navigation-button-visibility="Auto"` would hide the buttons when they aren't clickable.
- `navigation-button-visibility="Always"` would be the current behavior, showing disabled buttons when they aren't clickable.
---
- `navigation-buttons="All"` would be the current behavior, showing First, Previous, Next, and Last buttons.
- `navigation-buttons="OnlyNextAndPrevious"` and `navigation-buttons="OnlyFirstAndLast"` do what you would expect them to do.
