### ISSUE TITLE
works on my machine sticker

### ISSUE THREAD

**Issue by JustCallMeAD** [csharpfritz/CoreWiki#171]
In relation to you discussion about Jon's badge / sticker (https://blog.codinghorror.com/the-works-on-my-machine-certification-program/), I don't have the source files to his original sticker but I do have the source file to the logo below that I created..

**Comment by JustCallMeAD** [comment]
Yes, it was a slow day today ;)

![mock-fritz-mug](https://user-images.githubusercontent.com/4316208/42084439-fd635766-7bd0-11e8-9ce1-7126e222d0b9.jpg)

**Comment by csharpfritz** [comment]
That's AWESOME!  Can you share the logo so that I can make stickers? 

HUGE THANKS!

**Comment by csharpfritz** [comment]
Wait...  I would even have that mug made...  so cool!

**Comment by csharpfritz** [comment]
Is this logo now mine to use?  I’ve got a bunch of ideas

**Comment by JustCallMeAD** [comment]
Yes, it's your logo & you can do anything you wish with it!

**Comment by csharpfritz** [comment]
Thank you very much... I’m probably going to print stickers and a small handful of mugs to gauge interest. 

I’m working on other logos as well. 



Jeff

**Comment by JustCallMeAD** [comment]
Sounds awesome :)

**Comment by mozts2005** [comment]
Where can I buy the mug?

**Comment by JustCallMeAD** [comment]
@mozts2005 - If you look at @csharpfritz twitter account it sounds like he is thinking about getting some items made with this logo on it. I suggest that if anyone else is interested to let Jeff know so he can gauge interest & hopefully discuss his intentions further with everyone soon.

**Comment by csharpfritz** [comment]
I've set up a store on RedBubble:  https://www.redbubble.com/people/csharpfritz 

More to come...
