### ISSUE TITLE
Mapping our data

### ISSUE THREAD

**Issue by ezeraeze1** [csharpfritz/CoreWiki#173]
I always thought we were better off mapping our data to a view model before dumpling it to html for security reasons? How would we be able to go about it? Do we need automapper or perhaps something else?

**Comment by emo333** [comment]
But we aren’t using “Views” (thus far), we are using “RazorPages” and “page models”.

**Comment by parithon** [comment]
I agree that we still need to look into separating our concerns at some point. For example, when creating an Article we shouldn't be providing the entire model to the View as we do today. See: [public Article Article { get; set; }](https://github.com/csharpfritz/CoreWiki/blob/80c160115565c12cab4d3609b89da82aeaa08763/CoreWiki/Pages/Edit.cshtml.cs#L26)

Instead we should only be presenting the necessary fields to make the changes we desire. Then use AutoMapper to do the dirty left = right stuff.

Here is a good read on the topic: [ViewModels and AutoMapper in Razor Pages](https://www.mikesdotnetting.com/article/315/viewmodels-and-automapper-in-razor-pages)

**Comment by ashleybroughton** [comment]
@csharpfritz @emo333 @parithon @ezeraeze1 

Am I on the right track with what is being discussed here?

https://github.com/ashleybroughton/CoreWiki/commit/b159aee409013e0bf495467f0af2b20f71a94d19

**Comment by DannyAllegrezza** [comment]
@ashleybroughton yes, looks like you're on the right track!

**Comment by emo333** [comment]
This was brought up in Issue #64

**Comment by emo333** [comment]
I like what you did with this @ashleybroughton .  Are you going to open a PR?

**Comment by ashleybroughton** [comment]
Considering the things we saw on stream from Jimmy Bogard last night in that excellent [8 hour workshop](https://www.twitch.tv/videos/286991727) I think I will approach this in a slightly different way. So I won't be submitting a PR for how this currently stands.
