### ISSUE TITLE
If App_Data doesn't exist migration fails

### ISSUE THREAD

**Issue by parithon** [csharpfritz/CoreWiki#181]
It appears that the EF migration tool doesn't ensure the folder structure exists and will fail instead. Therefore, if new contributors start from scratch (i.e. a new clone), when they try to run CoreWiki it will fail during the migration process. #thisfeelsbad.

I suggest we include a README file in the App_Data folder and ignore any *.db inside it within our .gitignore instead of ignoring the entire directory.

**Comment by parithon** [comment]
Unfortunately PR #185 doesn't completely solve the problem; GIT ignores empty folders. When new contributors clone this repository the `App_Data` will still be missing and their initial run will fail until they manual create the `App_Data` folder. #

**Comment by csharpfritz** [comment]
Added README in commit 5451259b35d4cebea657317226f2efbe4012bf29
