### ISSUE TITLE
ApplicationDbContext Migrations Broken

### ISSUE THREAD

**Issue by parithon** [csharpfritz/CoreWiki#193]
When we refactored the `ApplicationDbContext` out of the CoreWiki project to it's own CoreWiki.Data project migrations no longer work.

**Comment by erwindevreugd** [comment]
As a workaround I copied the Migrations folder to CoreWiki.Data and ran
```dotnet ef database update --context applicationdbcontext --project "../CoreWiki.Data"```
from CoreWiki.
