### ISSUE TITLE
Rainbow Beard Challenge!

### ISSUE THREAD

**Issue by JustCallMeAD** [csharpfritz/CoreWiki#198]
Jeff has officially agreed to dye his beard rainbow colors in he can get to 5000 twitch followers by 20th of October 2018. Let's help him find that pot of gold :)

https://www.twitch.tv/csharpfritz

![dhqjan4xuaarbct](https://user-images.githubusercontent.com/4316208/42729741-3fe3cf7a-8825-11e8-80c6-04b7c2279a18.jpg)
![dhqkm5pvqaaacuy](https://user-images.githubusercontent.com/4316208/42729742-4014a15e-8825-11e8-9b02-a580ab7dcc39.jpg)

**Comment by JustCallMeAD** [comment]
Thumbs up if you think he should also dye his hair rainbow if we can get him to 6000 followers by 20th of October 2018 ;)

**Comment by TheNightBeat** [comment]
![fritzilla](https://user-images.githubusercontent.com/37749897/43037637-8df08a20-8d0f-11e8-98c6-ee3c23452eda.png)

**Comment by csharpfritz** [comment]
This should be in the Fritz.LiveStream repository... 

I think this is fun and can't wait to see how it turns out
