### ISSUE TITLE
Refactor EntityFramework models to DTO

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/CoreWiki#214]
This will allow us to break from Entity Framework.

- [ ] Create DTO classes
- [ ] Create fluent configuration for Entity Framework
- [ ] Remap Repository objects to return Entity objects

**Comment by ashleybroughton** [comment]
In progress. Help welcome. #223

**Comment by bravecobra** [comment]
Since we're talking about the persistence layer here, I would rename DTO to DAO.
