### ISSUE TITLE
Introduce MediatR

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/CoreWiki#216]

**Comment by MunkeyTH** [comment]
This may be a big jump! I will make a start and only do the first main article class to start.

**Comment by csharpfritz** [comment]
Yes it will...  if you're going to work on this, please submit the PR against the project_NewData branch

**Comment by MunkeyTH** [comment]
Thanks, to be sure can I clone down the latest copy from Dev, as I want to
make use of the DTO Ashley did then submit back to NewData branch?
Codingmunkey
