### ISSUE TITLE
Simplify pages which do similar things

### ISSUE THREAD

**Issue by ashleybroughton** [csharpfritz/CoreWiki#225]
The `All`, `Search`, and `Latest` pages, all display a list of articles based on some criteria.

What are your thoughts on simplifying this to a single `Search` page which can handle all three, based on the query it receives?

**Comment by erwindevreugd** [comment]
I have not looked at what all the implications would be but in my opinion: less duplicate code is better code.

Maybe put the article list inside a viewcomponent, let that render based on the page model and include that on the pages?

**Comment by csharpfritz** [comment]
This sounds like a GREAT simplification... and I think we could do that with some tricky routing to the same razor page.
