### ISSUE TITLE
Restrict UserAdmin to allow only those with the Administrators role access

### ISSUE THREAD

**Issue by cmjchrisjones** [csharpfritz/CoreWiki#247]
Currently anyone can access the user administration page and can assign role to anyone. 

This issue to to fix that only users in the Administrators role can access this page.

Other items which will be fixed:
- The User Admin navigation link will only be shown to authenticated users where they have the administrators role
- Removed the ability for the current logged in user to assign/remove themselves from a role!

PR to follow shortly

**Comment by aaronincincy** [comment]
This is going to make it important to either make the first registered user an admin, or have some other way of identifying an admin if none currently exist.

**Comment by cmjchrisjones** [comment]
@aaronincincy - very good point, I'll see if I can update the migrations maybe to add a default admin user as an interim solution. I guess this would be something that #182 covers in the [First Start Wizard](https://github.com/csharpfritz/CoreWiki/projects/4#card-11158893) project.

**Comment by cmjchrisjones** [comment]
I think this is OK to be closed now (I put fixes rather than closes in my commit message)!
