### ISSUE TITLE
Split domain logic from the database layer and the ui layer towards DDD and CQRS

### ISSUE THREAD

**Issue by bravecobra** [csharpfritz/CoreWiki#255]
Our current business object (or aggregate root) being  `Article` still has database specific attributes as well as display attributes. This should be split into different classes, namely the actual business object (BO) containing only the business logic, a DAO (Data Access Object) to store in some form of persistence (database) and a DTO (Data Transfer Object) to display the BO to the user. Some work has already been done in #223. A business object should be both view and database agnostic. It only is concerned about the business logic, not how it's persisted (DOA) nor how it is presented to the viewer (DTO). So those concerns need to be split out into different classes.
@jbogard showed us on stream how he uses Automapper to easily convert between DTO's and BO's or DAO's and BO's.
I would suggest splitting those responsibilities and placing those classes in their appropriate libraries as well

- Business objects in CoreWiki.Core
- DOA's in CoreWiki.Data with a corresponding mapper
- DTO's in CoreWiki.(Application) (I would suggest a separate library for that) with a corresponding mapper, which can then be consumed by the controllers of the website as @jbogard showed us. 

At the same time we can then start implementing #253, arriving a a cleaner architecture in the end, resembling more CQRS and DDD like. Again @jbogard showed us how in [ContosoUniversityDotNetCore-Pages](https://github.com/jbogard/ContosoUniversityDotNetCore-Pages) how to approach this. @julielerman also already hinted on stream that our current code-base suffers of this inadequacy.
We'll then also notice that some of the current Dto's are actually commands. ;)

As this refactoring will involve some major moving stuff around, I don't think we should start on this until we get an approval from our lord and master @csharpfritz as he'll have to do the merging into dev.

(Btw, tnx @jbogard for your talk on stream. I've been waiting for a hook to start working on this for a while now)

**Comment by bravecobra** [comment]
I would think this to be part of the [New data architecture](/csharpfritz/CoreWiki/projects/5) project.

**Comment by csharpfritz** [comment]
"Lord and Master"...  while I like the sound of that, I think I'm not overbearing or rough to deal with.

I like the way you're thinking @bravecobra and this accurately moves in the direction I agree we need to go.  I'll add this to the New Data project and we can start working in that branch

**Comment by bravecobra** [comment]
@csharpfritz Of course you're not, but I think you know my sense of humor by now.

**Comment by bravecobra** [comment]
Closes #173
