### ISSUE TITLE
File nesting preference

### ISSUE THREAD

**Issue by ashleybroughton** [csharpfritz/CoreWiki#259]
We talked about the default nesting a little bit on stream once, with how the HTML file is the default to be displayed in the solution explorer, with the .cs code behind page being nested underneath it.

Do we enforce a particular style of nesting, or should we add .filenesting.json to .gitignore and let each developer set their own preference?

I personally prefer having the .cs file front and center and the HTML file nested below it.

![image](https://user-images.githubusercontent.com/222825/43872369-0b543aae-9bb4-11e8-929a-6f92a8578a03.png)

```csharp
{
  "help": "https://go.microsoft.com/fwlink/?linkid=866610",
  "root": true,
  "dependentFileProviders": {
    "add": {
      "extensionToExtension": {
        "add": {
          ".cshtml": [ ".cshtml.cs" ]
        }
      }
    }
  }
}

```

**Comment by smabuk** [comment]
This doesn't affect the contents or placements of the files and therefore in my opinion it is definitely a preference for how a user decides to work (just like the choice of editor should be a choice), rather than something that should be included here.

**Comment by csharpfritz** [comment]
I think this is a fine idea for an addition to the project to allow contributors to work in a manner that they're most comfortable with
