### ISSUE TITLE
Change route definition

### ISSUE THREAD

**Issue by DevOpsChallengeBr** [csharpfritz/CoreWiki#27]
Currently we are using querystring to `[edit]` and `[delete]` an article. How to change the route to action/topic. 

**Ex:**
* /Edit/{Topic}
* /Delete/{Topic}

@csharpfritz:  I understand that for `[Details]`, `[Create]` and `[LatestChanges]` is resolved. **Correct?**
* /{Topic}
* /Create
* /LatestChanges

**Comment by csharpfritz** [comment]
I'm tempted to turn this around to:

/{Topic}/Edit
/[Topic}/Delete  ?  hmm...

**Comment by c17r** [comment]
@csharpfritz #114 has been merged, so this should probably be closed.
