### ISSUE TITLE
SqliteException: SQLite Error 19: 'UNIQUE constraint failed: Articles.Topic'.

### ISSUE THREAD

**Issue by DevOpsChallengeBr** [csharpfritz/CoreWiki#28]
When I try to save an new article with the same name as an existing one, it presents an exception **SQLite Error 19: 'UNIQUE constraint failed: Articles.Topic'**.

**EX:** 
* Topic = "HomePage"

**Comment by csharpfritz** [comment]
We should be enforcing this with a Key constraint...  definitely a bug and something we should detect and allow you to fix
