### ISSUE TITLE
Deploy to Azure button

### ISSUE THREAD

**Issue by shanselman** [csharpfritz/CoreWiki#283]
I'd like to be able to Deploy to Azure from here...likely need a .deployment file to point to the main website, and the badge.

**Comment by csharpfritz** [comment]
Deploy to Azure button instructions:  https://www.microsoft.com/developerblog/2017/01/17/the-deploy-to-azure-button/

**Comment by csharpfritz** [comment]
Tried the default button and it does not work... no log information is reported either

**Comment by fboucher** [comment]
The website and plan deployment worked.
It's the building of the application that failed.

There is 2 place to see the details of your deployment. From the resource group (provisioning the resources) and the webapp it self.

To see the Resource Group deployment detail, from the azure.portal.com select the resource group. Then from the left menu select the *Deployments* option.  You will see everything was successfully deployed.

![groupdeployment](https://user-images.githubusercontent.com/2404846/45264518-f140dd00-b40b-11e8-8459-87fb5556bdf6.png)

To see the WebApp deployment log (**where the error is**), from the resource group, click on the web site.  From that new blade, in the left menu select the Deployment options. Continue clicking until the logs... 

![websitelogs](https://user-images.githubusercontent.com/2404846/45264541-51378380-b40c-11e8-91da-ce0d5ab63111.png)

Here is the Error: 

```
 Restore operation started...
libman.json : error LIB002: The "node_modules/@fortawesome/fontawesome-free/" library could not be resolved by the "filesystem" provider [D:\home\site\repository\CoreWiki\CoreWiki.csproj]
  
  One or more libraries failed to restore
  
Failed exitCode=1, command=dotnet publish "D:\home\site\repository\CoreWiki\CoreWiki.csproj" --output "D:\local\Temp\8d6164d044cd1f9" --configuration Release
An error has occurred during web site deployment.
\r\nD:\Program Files (x86)\SiteExtensions\Kudu\77.10830.3542\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
```

Does it looks familliar to you? I didn't have the time to dig deeper for now, but wanted to give you the detail you were missing during your video.

**Comment by csharpfritz** [comment]
That tells me that npm install isn’t working on the deploy.  

Can we force the build process to build using our Cake script?


Jeff

**Comment by fboucher** [comment]
Yes.
I never try Cake, but to change the default build command you need to add a `.deployment` file at the root level of your repository.  

```
[config]
command = deploy.cmd
```

Look like to enable Cake to work with Kudu you will need a little bootstrap 

deploy.cmd
```
@echo off
IF NOT EXIST "Tools" (md "Tools")
IF NOT EXIST "Tools\Addins" (md "Tools\Addins")
nuget install Cake -ExcludeVersion -OutputDirectory "Tools"
.\Tools\Cake\Cake.exe build.cake -verbosity=Verbose
```
The above script will create the tools & addins folders, fetch Cake from NuGet(upgrade if a newer version exists) and launch the Cake build system with a C# script called deploy.cake.

ref: https://cakebuild.net/blog/2015/10/cake-addin-kudu

**Comment by fboucher** [comment]
Adding those 2 files made the deployment successful. However, the website is still empty. :(

```
========================================
Default
========================================
Executing task: Default
Finished executing task: Default

Task                          Duration            
--------------------------------------------------
Clean                         00:00:00.0394547    
NPM-Install                   00:00:51.6151939    
Restore                       00:01:27.9012019    
Build                         00:00:49.9863003    
Test                          00:00:12.9392202    
Default                       00:00:00.0000625    
--------------------------------------------------
Total:                        00:03:22.4814335    
```

**Comment by csharpfritz** [comment]
Fixed, updated on Readme and deployed!  Enjoy building your own Corewikis now!
