### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Eldorian** [csharpfritz/CoreWiki#318]
I haven't had a chance to pay attention to the development of this the last few months and saw that I could deploy the project to Azure and it worked great!

But now I'm lost on what to do. I get a message that says the default administrator account is enabled and to create a new user with an admin role and delete the account.

I created a new account, it doesn't have admin role. I can't figure out how to create a new user with an admin role nor do I know the default user that has admin role.

So I decided to go through the ReadMe - and there is absolutely nothing there about how to set this all up.

Y'all need some documentation :)

**Comment by RamblingGeekUK** [comment]
We do need documentation your right...  I will try and start putting some together over the next week, if I can. 

The default Admin username is : admin@corewiki.com, password: Admin@123.

I hope that helps.  Thanks 👍

**Comment by danielmpetrov** [comment]
That's a good point you brought up @Eldorian. I believe reworking the ReadMe is on our agenda.

I briefly experienced the same confusion the first time I launched CoreWiki.

To create a new administrator and get rid of this warning, you must do the following:
1. Register a new account (it won't have administrator rights for obvious reasons)
2. Sign in as the default administrator as @RamblingGeekUK mentions (admin@corewiki.com, password: Admin@123), and go to the User Admin page from the main menu up top
3. Scroll down, find the user you just registered, and give them the administrator role
4. From the main menu again, click the email address near the Logout button to open the profile manager
5. Click on the Personal Data sub-menu, and delete this default admin account

**Comment by csharpfritz** [comment]
We definitely need to improve the documentation around the product, and improve that getting started experience.

We'll tackle this over the next few weeks and hopefully it will be much easier to get started and learn how to use CoreWiki
