### ISSUE TITLE
Handling dateformatting

### ISSUE THREAD

**Issue by ArgTang** [csharpfritz/CoreWiki#322]
We need a way to handle date formatting. Right now we are displaying dates in the American way. But we should support other date-formats.

Suggestion:

- Setting default timezone for server
- Storing timezone for users in DB

Other options:
- We can find away to send date format from js, so we can render razor date for clients timezone.
- Check ip address and do a ballpark timezone on ip origin

**Comment by ArgTang** [comment]
Ah i see. I agree. se `/history` on an article, it has to be updated to fix the displayed date.
I might have time to fix it this week

**Comment by csharpfritz** [comment]
Fixed in project_FirstStart
