### ISSUE TITLE
Several methods need await to be properly Async

### ISSUE THREAD

**Issue by Wintermute21** [csharpfritz/CoreWiki#329]
Articles/Search/Impl/ArticlesDbSearchEngine.cs(22,56): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. 
Pages/CreateArticleFromLink.cshtml.cs(63,36): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
^ those are the two warnings I saw.

**Comment by lythix** [comment]
Happy to have a look at this one.
