### ISSUE TITLE
Missing jquery.validate.unobtrusive.js

### ISSUE THREAD

**Issue by summer600** [csharpfritz/CoreWiki#52]
I was watching the youtube video from the last stream (5-3-2018) and noticed at 2:19:40 that this js was giving a 404 in the developer tools. That is probably what is keeping the modelstate errors from displaying corrrectly.

**Comment by kim95748** [comment]
It's missing the dist folder name twice in:

CoreWiki/Pages/_ValidationScriptsPartial.cshtml

    ~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js

should be:

    ~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js

see pull request #55 for fix
