### ISSUE TITLE
Track Changes 

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/CoreWiki#7]
A history and list of changes to articles

**Comment by IvandroFabiaeFilhos** [comment]
hi,
For this feature make sense, we need define better the scope.

- Article have an owner?
- Differents authors can collaborate in an article or only owner and administrator can edit it?
- If exists versions, make sense, add compare functionality and show diff between it.

**Suggested:**

- Create aditional table (ArticleVersions) to storage versions. In ArticleVersions table add new [Version] column 

_- Edit/Detail Article_ 

- Add new functionality [Versions] which permite author navigate to [**Article Version List**]
- Add funcionality to Show Diff (Selection version A X Selection version B)

_- Articles List_

- Add new funcionality [Versions] to each article which permite author navigate to [**Article Version List**]

**Article Version List** - Allow Authors
------------------------------------------
- Show version list to selected article. Suggested Columns: [Changed By], [Changed Date] e [Change Type]
- To select two different versions and display the Diff.
- To select last version and delete it. 

**Sorry, my jungle English!**

**Comment by csharpfritz** [comment]
Lets use DiffPlex - https://github.com/mmanela/diffplex/ - for the diff operations
