### ISSUE TITLE
Contributing.md Pull Request section enhancement

### ISSUE THREAD

**Issue by parithon** [csharpfritz/CoreWiki#72]
Should the Pull Request Process section of [contributing.md](https://github.com/csharpfritz/CoreWiki/blob/dev/contributing.md#pull-request-process) include a step to rebase their branch prior to a creating a Pull Request to ensure we don't run into this: https://github.com/csharpfritz/CoreWiki/pull/63#issuecomment-391732636?

**Comment by csharpfritz** [comment]
Good idea.. let's find a statement we can add to the contributing doc
