### ISSUE TITLE
Ability to Create Links to Another Page and then Create that Page

### ISSUE THREAD

**Issue by essenbee** [csharpfritz/CoreWiki#79]
Need an easy way to create a link to another wiki page, even if that pages does not yet exist. Then an easy way to create that page from within the referring page. Something similar to how SharePoint wiki does this.

**Comment by csharpfritz** [comment]
Yes!  This is the same concept as #38

**Comment by essenbee** [comment]
Here are my initial thoughts on this, without using Wikitext, which I am not sure I understand:

- [ ] allow authors to create links to internal CoreWiki pages using the normal Markdown [text](link), (where the link does not begin with http/https) as they create/edit an article
- [ ]  on saving, use a regular expression to locate all such links in the article
- [ ] determine if the links already exist as slugs in the database
- [ ] present the author with the choice to create any articles that do not already exist, based on the above

These are the problems I can see:
- the author creates the slug that will be used, not the code
- should the code rewrite the slug to ensure a standard format? If so, how? 

I am no regular expression expert. Here is what I have come up with:

`(\[[\w\s.\-_:;\!\?]*[\]][\(])((?!(http|https))[\w\-_]*)([\)])`

- [ ] write unit tests that exercise the regular expression

**Comment by c17r** [comment]
@csharpfritz #123 has been merged, so this should probably be closed.
