### ISSUE TITLE
How to avoid multiple clicks when sending a new comment

### ISSUE THREAD

**Issue by DevOpsChallengeBr** [csharpfritz/CoreWiki#81]
If we click the Submit button several times the comment is duplicated. How to avoid?

**Comment by DevOpsChallengeBr** [comment]
The solution you choose should not be restricted to this button. It has how to implement for all buttons of the application. Is there any way?

**Comment by parithon** [comment]
This appears to be a race issue with the asynchronous [OnPostAsync ](https://github.com/csharpfritz/CoreWiki/blob/aad16b0d78c8ea245896cd89c7c5dcdf61fbfa96/CoreWiki/Pages/Details.cshtml.cs#L54) method. Before the method returns the [redirect request](https://github.com/csharpfritz/CoreWiki/blob/aad16b0d78c8ea245896cd89c7c5dcdf61fbfa96/CoreWiki/Pages/Details.cshtml.cs#L72) to the browser, the user is able to send additional submissions (thus submitting duplicate comments).
